version: "3.5"

services: 
    web:
        build: .
        container_name: web-api
        command: "python run.py"
        restart: on-failure:10
        ports: 
            - 5000:5000
        volumes: 
            - .:/app
    postgres:
        container_name: web-postgres
        image: postgres:12.4
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=test

volumes: 
    db-data: